In [24]:
import os 
os.chdir("C:\\Users\\smart\\Documents\\Bioinformatics\\Data Science for bioinformatics\\Week 11")
os.getcwd()

'C:\\Users\\smart\\Documents\\Bioinformatics\\Data Science for bioinformatics\\Week 11'

### Loading in the data 

In [25]:
import pandas as pd 
Table_1 = pd.read_excel('Table1.xlsx')
print("Table 1 \n", Table_1, "\n")

Table 1 
   Unnamed: 0  IRX4  OCT4  PAX6
0   patient1    11    10     1
1   patient2    13    13     3
2   patient3     2     4    10
3   patient4     1     3     9 



In [26]:
#Removing the unnamed column 
rmpt = Table_1.iloc[0:4,1:4]

In [27]:
print(rmpt)

   IRX4  OCT4  PAX6
0    11    10     1
1    13    13     3
2     2     4    10
3     1     3     9


In [28]:
#converting the rmpt data frame into a numpy array
import numpy as np
T1data = rmpt.to_numpy()
print("Table 1 data \n", T1data, "\n")

Table 1 data 
 [[11 10  1]
 [13 13  3]
 [ 2  4 10]
 [ 1  3  9]] 



In [29]:
# Calaculating the euclidean distances of the numpy array
from Bio.Cluster import distancematrix
distancesE = distancematrix(T1data, dist='e')
print("Euclidean distance \n", distancesE, "\n")

Euclidean distance 
 [array([], dtype=float64), array([5.66666667]), array([66.        , 83.66666667]), array([71.        , 93.33333333,  1.        ])] 



In [30]:
#Converting the results into a dataframe to make the results readable
Edf = pd.DataFrame(distancesE)
print("Euclidean distance dataframe \n", Edf, "\n")

Euclidean distance dataframe 
            0          1    2
0        NaN        NaN  NaN
1   5.666667        NaN  NaN
2  66.000000  83.666667  NaN
3  71.000000  93.333333  1.0 



In [31]:
# Calaculating the manhatthan distances of the numpy array
distancesM = distancematrix(T1data, dist='b')
print("Manhattan \n", distancesM, "\n")
#Converting the results into a dataframe to make the results readable
Mdf = pd.DataFrame(distancesM)
print("Manhattan distance dataframe \n", Mdf, "\n")

Manhattan 
 [array([], dtype=float64), array([2.33333333]), array([8., 9.]), array([8.33333333, 9.33333333, 1.        ])] 

Manhattan distance dataframe 
           0         1    2
0       NaN       NaN  NaN
1  2.333333       NaN  NaN
2  8.000000  9.000000  NaN
3  8.333333  9.333333  1.0 



## Clustering 

In [32]:
#Loading in the table 2 dataframe created in Rstudio
T2 = pd.read_csv('Table2.csv', index_col=0)
print("Table 2: \n\n", T2, "\n")

Table 2: 

            t1        t2        t3        t4        t5
g1  -0.209331  0.575628  0.747943  0.661025  0.024903
g2  -0.566134  1.102626 -1.326104 -0.697325 -1.195400
g3   0.552118  0.815165 -0.793938 -0.304374  0.754580
g4   0.800665 -0.996414 -0.824040  1.121050  0.644800
g5   0.072447  0.940999 -0.362187  0.112090  1.117452
g6   1.928389 -0.184790  0.518182  1.033102 -0.368495
g7  -0.818658 -1.061320 -1.627024  1.534679  1.163095
g8  -0.136280  0.858841  0.973422  0.589590  1.229153
g9   1.912244  0.189364 -0.619768  2.082375  0.472258
g10  0.092512 -0.321310  0.269982  0.480788 -1.204305 



In [33]:
#Importing sklearn
import sklearn
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
#scaling the data to prepare it for clusting 
scale = StandardScaler()
scaledT2 = scale.fit_transform(T2)
print("Scaled Table 2: \n", scaledT2, "\n")

Scaled Table 2: 
 [[-6.36801051e-01  5.05676644e-01  1.24425402e+00 -3.47566334e-04
  -2.73314689e-01]
 [-1.03393745e+00  1.20011620e+00 -1.20813684e+00 -1.71859525e+00
  -1.66940050e+00]
 [ 2.10721990e-01  8.21321659e-01 -5.78894421e-01 -1.22153091e+00
   5.61472070e-01]
 [ 4.87363994e-01 -1.56584565e+00 -6.14487212e-01  5.81561311e-01
   4.35877477e-01]
 [-3.23171451e-01  9.87135950e-01 -6.83839474e-02 -6.94723944e-01
   9.76615122e-01]
 [ 1.74256653e+00 -4.96347216e-01  9.72581204e-01  4.70312360e-01
  -7.23381360e-01]
 [-1.31500707e+00 -1.65137429e+00 -1.56395084e+00  1.10478192e+00
   1.02883294e+00]
 [-5.55493303e-01  8.78873926e-01  1.51086550e+00 -9.07098954e-02
   1.10440631e+00]
 [ 1.72459627e+00 -3.31391061e-03 -3.72952230e-01  1.79759109e+00
   2.38481651e-01]
 [-3.00838449e-01 -6.76243322e-01  6.79104770e-01 -2.28339108e-01
  -1.67958903e+00]] 



In [34]:
#Obtaining the euclidean distances of table 2
from Bio.Cluster import distancematrix
distancesET2 = distancematrix(scaledT2, dist='e')
print("Table 2 Euclidean distance: \n", distancesET2, "\n")

Table 2 Euclidean distance: 
 [array([], dtype=float64), array([2.31112305]), array([1.265991  , 1.46249476]), array([1.97028842, 4.0080477 , 1.80865619]), array([0.81953362, 1.97985933, 0.20460537, 1.87884256]), array([1.43266576, 4.20575248, 2.20061151, 1.31888077, 2.35978035]), array([3.18314926, 4.71770481, 3.00851363, 0.95653876, 2.68462851,
       4.11792905]), array([0.42464987, 3.61381881, 1.30620569, 2.49604173, 0.5881773 ,
       2.22352318, 3.57368495]), array([2.38902873, 5.15177326, 2.44673436, 1.10965636, 2.40471613,
       0.94814285, 2.89568177, 2.76826784]), array([0.7717574 , 1.96816146, 2.01914834, 1.64343456, 2.11980081,
       1.13928838, 3.22469562, 2.1889273 , 2.6890864 ])] 



In [35]:
#put the euclideandistances into a dataframe
DT2 = pd.DataFrame(distancesET2)
print("Table 2 Euclidean distance dataframe: \n", DT2, "\n")

Table 2 Euclidean distance dataframe: 
           0         1         2         3         4         5         6  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1  2.311123       NaN       NaN       NaN       NaN       NaN       NaN   
2  1.265991  1.462495       NaN       NaN       NaN       NaN       NaN   
3  1.970288  4.008048  1.808656       NaN       NaN       NaN       NaN   
4  0.819534  1.979859  0.204605  1.878843       NaN       NaN       NaN   
5  1.432666  4.205752  2.200612  1.318881  2.359780       NaN       NaN   
6  3.183149  4.717705  3.008514  0.956539  2.684629  4.117929       NaN   
7  0.424650  3.613819  1.306206  2.496042  0.588177  2.223523  3.573685   
8  2.389029  5.151773  2.446734  1.109656  2.404716  0.948143  2.895682   
9  0.771757  1.968161  2.019148  1.643435  2.119801  1.139288  3.224696   

          7         8  
0       NaN       NaN  
1       NaN       NaN  
2       NaN       NaN  
3       NaN       NaN  
4       NaN   

In [36]:
#Calculating spearmans rank
distancesST2 = distancematrix(scaledT2, dist='s')
print("Table 2 Spearman's rank correlation': \n", distancesST2, "\n")

Table 2 Spearman's rank correlation': 
 [array([], dtype=float64), array([0.9]), array([1.1, 0.3]), array([1.6, 1.7, 1.7]), array([0.7, 0.4, 0.1, 1.9]), array([1.1, 0.8, 1.5, 0.7, 1.6]), array([1.5, 1.9, 1.6, 0.1, 1.7, 1.1]), array([0.3, 1.1, 0.9, 1.6, 0.5, 1.4, 1.3]), array([1.7, 1.5, 1.4, 0.1, 1.7, 0.9, 0.2, 1.8]), array([0.5, 1.2, 1.8, 0.8, 1.6, 0.3, 1. , 0.9, 1.1])] 



In [37]:
#converting the correlation matrix into a dataframe
ST2 = pd.DataFrame(distancesET2)
print("Table 2 Spearman’s rank correlation dataframe: \n", ST2, "\n")

Table 2 Spearman’s rank correlation dataframe: 
           0         1         2         3         4         5         6  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1  2.311123       NaN       NaN       NaN       NaN       NaN       NaN   
2  1.265991  1.462495       NaN       NaN       NaN       NaN       NaN   
3  1.970288  4.008048  1.808656       NaN       NaN       NaN       NaN   
4  0.819534  1.979859  0.204605  1.878843       NaN       NaN       NaN   
5  1.432666  4.205752  2.200612  1.318881  2.359780       NaN       NaN   
6  3.183149  4.717705  3.008514  0.956539  2.684629  4.117929       NaN   
7  0.424650  3.613819  1.306206  2.496042  0.588177  2.223523  3.573685   
8  2.389029  5.151773  2.446734  1.109656  2.404716  0.948143  2.895682   
9  0.771757  1.968161  2.019148  1.643435  2.119801  1.139288  3.224696   

          7         8  
0       NaN       NaN  
1       NaN       NaN  
2       NaN       NaN  
3       NaN       NaN  
4    

In [38]:
#Performing hierachal cliustering on the T2 data using Euclidean distance
from Bio.Cluster import treecluster
T2tree = treecluster(data=scaledT2)
print(T2tree)

(4, 2): 0.204605
(7, 0): 0.42465
(8, 5): 0.948143
(6, 3): 0.956539
(-1, -2): 1.30621
(9, 1): 1.96816
(-3, -5): 2.76827
(-4, -7): 4.11793
(-6, -8): 5.15177


In [39]:
#Performing hierachal cliustering on the T2 data using Spearman's rank correlation 
T2tree2 = treecluster(data=scaledT2, dist='s')
print(T2tree2)

(4, 2): 0.1
(6, 3): 0.1
(8, -2): 0.2
(5, 9): 0.3
(7, 0): 0.3
(-1, 1): 0.4
(-6, -5): 1.1
(-4, -3): 1.1
(-8, -7): 1.9


In [40]:
#Performing hierachal cliustering on the T2 data using Euclidean distance and Spearman's rank correlation 
T2tree3 = treecluster(data=None, distancematrix=distancesST2)
print(T2tree3)

(4, 2): 0.1
(6, 3): 0.1
(8, -2): 0.2
(5, 9): 0.3
(7, 0): 0.3
(-1, 1): 0.4
(-6, -5): 1.1
(-4, -3): 1.1
(-8, -7): 1.9
